name: Build and Deploy Vue.js App to GitHub Pages

on:
  push:
    branches:
      - main  # ou o branch principal do seu repositório
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Escolha a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Build the Vue.js app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  validation:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_91.0.4472.77-1_amd64.deb
          sudo dpkg -i google-chrome-stable_91.0.4472.77-1_amd64.deb
          sudo apt-get install -f -y

      - name: Install Selenium and Chromedriver
        run: |
          npm install selenium-webdriver
          npm install chromedriver

      - name: Run Selenium tests
        run: npm run test:selenium

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: selenium-artifacts
          path: '*.png'